### ISSUE TITLE
Desktop app now no longer works

### ISSUE THREAD

**Issue by Delwddrylliwr** [Delwddrylliwr/cartolan#153]
Traceback (most recent call last):
  File "main_game.py", line 277, in <module>
    client_visual.play_game()
  File "main_game.py", line 183, in play_game
    self.game_vis = GameVisualisation(self.game, self.dimensions, self.origin)
  File "C:\Users\t-wilkinson\cartolan_sim\live_visuals.py", line 91, in __init__
    self.init_GUI()
  File "C:\Users\t-wilkinson\cartolan_sim\live_visuals.py", line 126, in init_GUI
    self.init_graphics()
  File "C:\Users\t-wilkinson\cartolan_sim\live_visuals.py", line 210, in init_graphics
    self.chest_tile_library[tile_name] = pygame.transform.scale(tile_image, [self.chest_tile_size, self.chest_tile_size])
AttributeError: 'GameVisualisation' object has no attribute 'chest_tile_size'

**Comment by Delwddrylliwr** [comment]
Deprecated
