### ISSUE TITLE
Bug: auto-actions used in response to City buy decisions

### ISSUE THREAD

**Issue by Delwddrylliwr** [Delwddrylliwr/cartolan#212]
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "web_server.py", line 372, in join_game
    self.game.game_over = self.game.play_round()
  File "/home/twilkinson/cartolan/game.py", line 193, in play_round
    player.continue_turn(adventurer)
  File "/home/twilkinson/cartolan/players_human.py", line 327, in continue_turn
    self.continue_move(adventurer)
  File "/home/twilkinson/cartolan/players_human.py", line 270, in continue_move
    moved = adventurer.move(move_map[move_coords[0]].get(move_coords[1]))
  File "/home/twilkinson/cartolan/beginner.py", line 261, in move
    self.current_tile.visit_city(self, False)
  File "/home/twilkinson/cartolan/advanced.py", line 366, in visit_city
    super().visit_city(adventurer, abandoned)
  File "/home/twilkinson/cartolan/regular.py", line 413, in visit_city
    super().visit_city(adventurer, abandoned)
  File "/home/twilkinson/cartolan/beginner.py", line 753, in visit_city
    self.buy_agents(adventurer)
  File "/home/twilkinson/cartolan/beginner.py", line 837, in buy_agents
    if not adventurer.check_tile_available(tile):
  File "/home/twilkinson/cartolan/regular.py", line 366, in check_tile_available
    elif tile.agent is None:
AttributeError: 'bool' object has no attribute 'agent'

**Comment by Delwddrylliwr** [comment]
Introduced removal of auto-actions for any of the city-based buying options.
