### ISSUE TITLE
Undo during Adventurer or Agent buying crashes

### ISSUE THREAD

**Issue by Delwddrylliwr** [Delwddrylliwr/cartolan#232]
Jim has banked 8 in their Vault
Do you want to place an agent, and where?
Adding movement options that will be available next move, to allow skipping of actions
Highlighting the tile where Jim's Adventurer #1 can buy
Prompting the Jim player for input
data sent to client at ('::ffff:82.32.5.190', 37122, 0, 0)
data sent to client at ('::ffff:82.32.5.190', 54132, 0, 0)
Click coordinate Input received from client... 662, 251
2021-08-26 14:34 GMT
Player chose coordinates within the undo button, with vertical: 251
data sent to client at ('::ffff:82.32.5.190', 54132, 0, 0)
data sent to client at ('::ffff:82.32.5.190', 37122, 0, 0)
data sent to client at ('::ffff:82.32.5.190', 54132, 0, 0)
Click coordinate Input received from client... 1422, 670
2021-08-26 14:34 GMT
Player chose coordinates within the undo button, with vertical: 670
data sent to client at ('::ffff:82.32.5.190', 54132, 0, 0)
Confirmed with all clients that turn can be undone.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "web_server.py", line 400, in join_queue
    if not self.start_game(game_id): #testing the negative because otherwise it will take until game conclusion to return
  File "web_server.py", line 462, in start_game
    self.game.game_over = self.game.play_round()
  File "/home/twilkinson/cartolan/game.py", line 193, in play_round
    player.continue_turn(adventurer)
  File "/home/twilkinson/cartolan/players_human.py", line 347, in continue_turn
    self.continue_move(adventurer)
  File "/home/twilkinson/cartolan/players_human.py", line 283, in continue_move
    moved = adventurer.move(compass_point)
  File "/home/twilkinson/cartolan/beginner.py", line 261, in move
    self.current_tile.visit_city(self, False)
  File "/home/twilkinson/cartolan/advanced.py", line 368, in visit_city
    super().visit_city(adventurer, abandoned)
  File "/home/twilkinson/cartolan/regular.py", line 413, in visit_city
    super().visit_city(adventurer, abandoned)
  File "/home/twilkinson/cartolan/beginner.py", line 753, in visit_city
    self.buy_agents(adventurer)
  File "/home/twilkinson/cartolan/beginner.py", line 837, in buy_agents
    if not adventurer.check_tile_available(tile):
  File "/home/twilkinson/cartolan/regular.py", line 366, in check_tile_available
    elif tile.agent is None:
AttributeError: 'bool' object has no attribute 'agent'

**Comment by Delwddrylliwr** [comment]
Identified as an issue with using menus generally while prompted for a specific tile input when buying Agents.

Fixed by extending the exclusions applied to handle the input as originally intended.
